# Generated by Django 4.2.7 on 2023-12-19 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_items_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='age',
            field=models.IntegerField(default=datetime.datetime(2023, 12, 19, 5, 45, 28, 504040, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
