# Generated by Django 4.2.7 on 2023-12-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_items_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
        migrations.AddField(
            model_name='items',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='age',
            field=models.IntegerField(default=''),
        ),
    ]
